version: "3"

services:
  api:
    build: .
    image: spaceenterbs/jimgabang-api:latest
    ports: 
      - "8000:8000"
    env_file:
      - .env.prod
  
  database:
    image: mongo:7.0.1
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: