version: "3"

services:
  api:
    build: .
    image: jimgabang-api:latest
    ports: 
      - "8000:80"
    env_file:
      - .env.prod

  # nginx:
  #   image: nginx:1.24.0-alpine
  #   ports:
  #     - "80:80" # Nginx가 클라이언트의 요청을 받아서 내부 네트워크의 API 서비스(8000번 포트)로 전달한다.
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./certs:/etc/ssl/certs
  
  database:
    image: mongo:7.0.1
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: